name: Push main to Prod S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "frontend/"
          # The directory to scan
          arguments: --ignore-status-codes 999
          # The arguments to pass to HTMLProofer

      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        # Prod Account
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::585008089082:role/GitHub-Web-Site
          aws-region: us-east-1

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync frontend/ s3://milan-excavating-com-prod && aws cloudfront create-invalidation --distribution-id ESCL5DDDPNVFP --paths "/*"
